# Generated by Django 3.1.2 on 2021-01-11 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reg_jounals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabel',
            name='t_user',
        ),
        migrations.AddField(
            model_name='departments',
            name='dep_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Табельщик'),
        ),
    ]
