# Generated by Django 3.1.2 on 2020-12-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0002_auto_20201228_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='t_dep',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reg_jounals.departments', verbose_name='Подразделение '),
        ),
    ]
