# Generated by Django 3.1.2 on 2020-12-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_jounals', '0003_tabel_t_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='t_workdays',
            field=models.IntegerField(default=0, verbose_name='Кол-во явок (часы)'),
        ),
    ]
