# Generated by Django 3.1.2 on 2021-08-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURV', '0003_tabel_unloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelitem',
            name='v_hours',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Часов неявок'),
        ),
        migrations.AlterField(
            model_name='tabelitem',
            name='w_hours',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Часов отработано'),
        ),
    ]
